version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-productos
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  producto-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producto-service
    ports:
      - "8084:8084"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongodb_data:

